### ISSUE TITLE
Installation crash in android qpython

### ISSUE THREAD

**Issue by bukzor** [bukzor/ohai#1]
/data/user/0/org.qpython.qpy3/files/bin/qpython-android5.sh "/storage/emulated/0/qpython/scripts3/.last_tmp.py" && exit
/0/qpython/scripts3/.last_tmp.py" && exit        <
Input pip commands, ie: pip install {module}
-->pip install ohai

Downloading/unpacking ohai
  Real name of requirement ohai is ohai
  Downloading ohai-1%210.tar.gz
  Running setup.py egg_info for package ohai
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/storage/emulated/0/qpython/cache/pip-build/ohai/setup.py", line 84, in <module>
        exit(main())
      File "/storage/emulated/0/qpython/cache/pip-build/ohai/setup.py", line 63, in main
        long_description=dedent(Install.__doc__),
      File "/data/user/0/org.qpython.qpy3/files/lib/python3.2/python32.zip/textwrap.py", line 352, in dedent
    TypeError: expected string or buffer
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/storage/emulated/0/qpython/cache/pip-build/ohai/setup.py", line 84, in <module>

    exit(main())

  File "/storage/emulated/0/qpython/cache/pip-build/ohai/setup.py", line 63, in main

    long_description=dedent(Install.__doc__),

  File "/data/user/0/org.qpython.qpy3/files/lib/python3.2/python32.zip/textwrap.py", line 352, in dedent

TypeError: expected string or buffer

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /storage/emulated/0/qpython/cache/pip-build/ohai
Storing complete log in /sdcard/qpython/.pip/pip.log
-->

#[QPython] Press enter to exit

**Comment by asottile** [comment]
I bet the python is running with `-OO` (optimizations + strip docstrings)

```python
class C(object):
    """hello"""

print(repr(C.__doc__))
```

```console
$ python -OO test.py
None
```

**Comment by bukzor** [comment]
Oh... dummies.
